# Generated by Django 5.2 on 2025-07-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('delivery_request', 'New Delivery Request'), ('delivery_accepted', 'Delivery Request Accepted'), ('delivery_rejected', 'Delivery Request Rejected'), ('delivery_completed', 'Delivery Completed'), ('availability_update', 'Delivery Partner Availability Update'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('group_buying_started', 'Group Buying Session Started'), ('group_buying_joined', 'Someone Joined Your Group Buying'), ('group_buying_completed', 'Group Buying Session Completed'), ('system_announcement', 'System Announcement'), ('profile_update', 'Profile Update Required'), ('verification_complete', 'Account Verification Complete')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('variables_help', models.TextField(blank=True, help_text='Available variables for this template (e.g., {user_name}, {order_id})')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_delivery_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_group_buying', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_delivery_updates', models.BooleanField(default=True)),
                ('push_payment_updates', models.BooleanField(default=True)),
                ('push_group_buying', models.BooleanField(default=True)),
                ('push_system_announcements', models.BooleanField(default=False)),
                ('inapp_order_updates', models.BooleanField(default=True)),
                ('inapp_delivery_updates', models.BooleanField(default=True)),
                ('inapp_payment_updates', models.BooleanField(default=True)),
                ('inapp_group_buying', models.BooleanField(default=True)),
                ('inapp_system_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('delivery_request', 'New Delivery Request'), ('delivery_accepted', 'Delivery Request Accepted'), ('delivery_rejected', 'Delivery Request Rejected'), ('delivery_completed', 'Delivery Completed'), ('availability_update', 'Delivery Partner Availability Update'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('group_buying_started', 'Group Buying Session Started'), ('group_buying_joined', 'Someone Joined Your Group Buying'), ('group_buying_completed', 'Group Buying Session Completed'), ('system_announcement', 'System Announcement'), ('profile_update', 'Profile Update Required'), ('verification_complete', 'Account Verification Complete')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
